### ISSUE TITLE
Populating "3.5.0" instead of "3.5"

### ISSUE THREAD

**Issue by scottkennedy** [Commit451/updatewrapper#2]
The plugin is currently updating `gradle-wrapper.properties` to `distributionUrl=https\://services.gradle.org/distributions/gradle-3.5.0-all.zip`, but it should be `distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-all.zip`.

**Comment by Jawnnypoo** [comment]
Dang yeah, looks like they do different versioning in GitHub then they do in the actual distribution. That is frustrating. We might have to change this up a bit to where it looks toward and parses https://services.gradle.org/distributions/ instead of using the GitHub API to get the latest release number. I am going to raise an issue with them too.

**Comment by Jawnnypoo** [comment]
Suggestion from https://github.com/gradle/gradle/issues/1799 is to use the REL tag

**Comment by Jawnnypoo** [comment]
I went the route of getting the latest by parsing gradle.org instead. We will see how that goes. Thanks for reporting!
